#!/usr/bin/lua
local site = require('gluon.site')
local uci = require('simple-uci').cursor()

if site.domain_changer then
  local uci_domain_changer = uci:get_first('gluon-domain-changer', 'domain-changer')
  uci:set('gluon-domain-changer', uci_domain_changer, 'url', site.domain_changer.url())
  uci:commit('gluon-domain-changer')
end
