#!/bin/sh
cat <<EOF > /etc/rc.button/rfkill
#!/bin/sh
# this gluon/openWRT file is overwritten on purpose to deactivate wifi switch

logger -t rfkill "WiFi On/Off pressed. Doing nothing."

# still use normal exit code
exit 0
EOF

chmod a+x /etc/rc.button/rfkill
