
include $(TOPDIR)/rules.mk

PKG_NAME:=gluon-config-mode-adv-stats
PKG_VERSION:=1

include ../gluon.mk

define Package/gluon-config-mode-adv-stats
  TITLE:=Toggle adv-stats
    DEPENDS:=+gluon-config-mode-core
    endef

$(eval $(call BuildPackageGluon,gluon-config-mode-adv-stats))
